-- Migration file created for Namaste_code schema
CREATE TABLE IF NOT EXISTS public."Namaste_code" (
    "Sr No." bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TM2 Code" character varying NOT NULL,
    "Ayurveda Code" character varying,
    "Name English" character varying,
    "Namc Term Devanagari" character varying,
    "Hinglish" character varying
);

ALTER TABLE public."Namaste_code" ENABLE ROW LEVEL SECURITY;
